version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: gunicorn exif.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./exif/:/usr/src/exif/
      - ./victim/:/usr/src/victim/
      - media_data:/usr/src/exif/media
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DEFAULT_USER=pontifex
      - DEFAULT_PASSWORD=apexlegends?
      - NGINX_HOST=nginx
      - PHANTOMJS_HOST=phantomjs
      - PHANTOMJS_PORT=8910
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - DEBUG=False
    depends_on:
      - db
      - rabbitmq

  nginx:
    build: ./nginx
    ports:
      - 19008:80
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - media_data:/usr/src/exif/media

#  https://hub.docker.com/r/anapsix/alpine-java/
  phantomjs:
    image: wernight/phantomjs
    container_name: phantomjs
    restart: always
    ports:
      - 8910
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"
    environment:
      - DEFAULT_USER=pontifex
      - DEFAULT_PASSWORD=apexlegends?

  rabbitmq:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    image: "rabbitmq:3-management"
    ports:
      - 15672
      - 5672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    command:  "rabbitmq-server"

volumes:
  postgres_data:
  media_data:
